// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_seqs_pri
NumericVector find_seqs_pri(NumericVector v, NumericVector r, NumericVector t, double start_incl, double year_turn, double cum_turn, int tolerance);
RcppExport SEXP _ESOT_find_seqs_pri(SEXP vSEXP, SEXP rSEXP, SEXP tSEXP, SEXP start_inclSEXP, SEXP year_turnSEXP, SEXP cum_turnSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type start_incl(start_inclSEXP);
    Rcpp::traits::input_parameter< double >::type year_turn(year_turnSEXP);
    Rcpp::traits::input_parameter< double >::type cum_turn(cum_turnSEXP);
    Rcpp::traits::input_parameter< int >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(find_seqs_pri(v, r, t, start_incl, year_turn, cum_turn, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// find_seqs_sta
NumericVector find_seqs_sta(NumericVector v, NumericVector r, NumericVector t, double start_incl, double year_turn, double cum_turn, int tolerance);
RcppExport SEXP _ESOT_find_seqs_sta(SEXP vSEXP, SEXP rSEXP, SEXP tSEXP, SEXP start_inclSEXP, SEXP year_turnSEXP, SEXP cum_turnSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type start_incl(start_inclSEXP);
    Rcpp::traits::input_parameter< double >::type year_turn(year_turnSEXP);
    Rcpp::traits::input_parameter< double >::type cum_turn(cum_turnSEXP);
    Rcpp::traits::input_parameter< int >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(find_seqs_sta(v, r, t, start_incl, year_turn, cum_turn, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ESOT_find_seqs_pri", (DL_FUNC) &_ESOT_find_seqs_pri, 7},
    {"_ESOT_find_seqs_sta", (DL_FUNC) &_ESOT_find_seqs_sta, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ESOT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
