utils::globalVariables(c("country_id", "country_text_id", "country_name", "year",
                          "v2clstown_osp",
                          "econ_type", "econ_start_year", "econ_end_year", "econ_id", "econ_reg_type",
                          "econ_trans", "econ_regch_event", "econ_regch_censored",
                          "econ_regch_year", "econ_regch_filled",
                          "econ_stabilized", "econ_closed",
                          "mkt_trans_dum", "state_breakdown_dum",
                          "priv_ep", "priv_ep_id", "priv_ep_start_year", "priv_ep_end_year",
                          "priv_ep_termination", "priv_ep_prch",
                          "priv_ep_ptr", "priv_ep_subdep",
                          "priv_ep_outcome", "priv_ep_outcome_agg", "priv_ep_censored",
                          "priv_ep_uncertain",
                          "stat_ep", "stat_ep_id", "stat_ep_start_year", "stat_ep_end_year",
                          "stat_ep_termination", "stat_ep_prch",
                          "stat_ep_pbr", "stat_ep_subreg",
                          "stat_ep_outcome", "stat_ep_outcome_agg", "stat_ep_censored",
                          "stat_ep_uncertain",
                          "codingstart", "codingend", "gapstart1", "gapstart2", "gapstart3",
                          "gapend1", "gapend2", "gapend3",
                          "gapstart", "gapend",
                          "codingstart2", "episode_id", "character_id",
                          "last_ch_year", "newid", "origsample",
                          "overlap", "ep_type", "episode",
                          "priv_eps", "stat_eps", "countries",
                          "breakdown", "mkt_trans",
                          "overlap_eps", "overlap_period"))
