# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify sequences of potential privatization episodes
#'
#' This is a subfunction (c++) of ERT::get_eps see the
#' documentation of ERT::get_eps (?get_eps) for details on
#' parameters, etc.
#'
find_seqs_pri <- function(v, r, t, start_incl = 0.04, year_turn = -0.12, cum_turn = -0.4, tolerance = 5L) {
    .Call('_ESOT_find_seqs_pri', PACKAGE = 'ESOT', v, r, t, start_incl, year_turn, cum_turn, tolerance)
}

#' Identify sequences of potential statization episodes
#'
#' This is a subfunction (c++) of ESOT::get_eps see the
#' documentation of ESOT::get_aut (?get_eps) for details on
#' parameters, etc.
#'
find_seqs_sta <- function(v, r, t, start_incl = -0.04, year_turn = 0.12, cum_turn = 0.4, tolerance = 5L) {
    .Call('_ESOT_find_seqs_sta', PACKAGE = 'ESOT', v, r, t, start_incl, year_turn, cum_turn, tolerance)
}

